### ISSUE TITLE
Potential server side errors because of configuration

### ISSUE THREAD

**Issue by erikburt** [raymondfeng/loopback4-example-auth0#1]
This snippet [here](https://github.com/raymondfeng/loopback4-example-auth0/blob/master/src/authentication-strategies/auth0.ts#L36):

```javascript
...
const jwtCheck = jwt({
      secret: jwks.expressJwtSecret({
        cache: true,
        rateLimit: true,
        jwksRequestsPerMinute: 5,
        jwksUri: auth0Config.jwksUri,
      }),
...
```

will lead to "429 Too Many Request" responses from auth0 because the authentication strategy is instantiated once per request and therefore the secret object is as well.

I'm guessing the `cache: true` is meant so upon multiple requests it will not hit the configured `jwksUri` given a certain time frame - as it is "cached". However, I found that I was getting 429 errors from auth0 and subsequently a 500 error response from my loopback API and this is because the `jwk.expressJwtSecret` object was getting instantiated upon every request and sending a request to the jwksUri upon every instantiation.

The solution for me was to create the secret object at application boot (adding a secret property to the `Auth0Config`) and fetching the secret object from the injected options object within the strategy.

Leaving as is will only create errors if the amount of requests being sent to the API exceeds the rate limits set by auth0. However, it does remove the cache, and rate limiting functionality of the library when implemented like so and will then rely on the rate limits set by auth0. However, with multiple clients this will limit them all if the limit is exceeded.

**Comment by raymondfeng** [comment]
@erikburt Good catch. Please check if the latest master fixes the issue. I refactored `jwtCheck` to a singleton service so that caching should be applied across requests.

**Comment by erikburt** [comment]
It appears to be working well. It is also a much more elegant solution than mine.
