### ISSUE TITLE
Error after running npm update

### ISSUE THREAD

**Issue by shnplr** [raymondfeng/loopback4-example-auth0#4]
I'm trying to use this example with my project which has more recent dependencies. After cloning this project and running npm update, npm run clean && npm run build produces the following error which is the same as what I'm seeing in my project:

```
src/authentication-strategies/auth0.ts:28:45 - error TS2345: Argument of type '(err?: Error | undefined) => void' is not assignable to parameter of type 'NextFunction'.
  Types of parameters 'err' and 'deferToNext' are incompatible.
    Type '"router"' is not assignable to type 'Error | undefined'.

28       this.jwtCheck(request, this.response, (err?: Error) => {
                                               ~~~~~~~~~~~~~~~~~~
```

Can this be resolved without downgrading packages?

**Comment by raymondfeng** [comment]
Just updated dependencies and fixed the compilation errors.

**Comment by shnplr** [comment]
The build problem is resolved but now seeing this:-
```
$ curl http://localhost:3000/greet -H "Authorization: Bearer $TOKEN"
    at .../loopback4-example-auth0/node_modules/jwks-rsa/lib/JwksClient.js:102:23
    at .../loopback4-example-auth0/node_modules/jwks-rsa/lib/wrappers/request.js:42:12
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Unhandled error in GET /greet: 500 JwksError: <HTML><HEAD>
```

To confirm I checked out fe0c63e8dc1ec90406a5c5fdbed59485277a0576 which tested fine with my jwks/scope. Then `git checkout master` && `npm i` and `npm start` and had the error.

**Comment by shnplr** [comment]
Temporary solution to downgrade in package.json

```
"jwks-rsa": "1.6.0"
```

Newer version switched from request to axios which has issue with http proxy

**Comment by raymondfeng** [comment]
@shnplr Are you behind a proxy? I don't see the problem.
